get sdk version from intrinsic_sdk_bundle_library_py (#134)
* get sdk version from intrinsic_sdk_bundle_library_py

Signed-off-by: Aaron Chong <aaronchongth@gmail.com>

* revert and catch

Signed-off-by: Aaron Chong <aaronchongth@gmail.com>

* put fix back in

Signed-off-by: Aaron Chong <aaronchongth@gmail.com>

---------

Signed-off-by: Aaron Chong <aaronchongth@gmail.com>

diff --git a/.github/workflows/deploy_container_images.yaml b/.github/workflows/deploy_container_images.yaml
--- a/.github/workflows/deploy_container_images.yaml
+++ b/.github/workflows/deploy_container_images.yaml
@@ -34,6 +34,11 @@ jobs:
       # Extract the intrinsic sdk version being used.
       - name: Get intrinsic-ai/sdk Version
         run: echo "INTRINSIC_AI_SDK_VERSION=${{ needs.build-test.outputs.intrinsic_ai_sdk_version }}" >> $GITHUB_ENV
+      - run: |
+          if [ -z "$INTRINSIC_AI_SDK_VERSION" ]; then
+            echo "Error: INTRINSIC_AI_SDK_VERSION is empty!" >&2
+            exit 1
+          fi
       - run: echo "The Intrinsic SDK version being used is ${{ env.INTRINSIC_AI_SDK_VERSION }}"
 
       # Login to ghcr.io.
